name: Build Maven JAR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Copy openai-code-review-sdk JAR
        run: |
          mkdir -p ./libs
          cp openai-code-review-sdk/target/openai-code-review-sdk-1.0-SNAPSHOT.jar ./libs/

      - name: Run code review
        run: java -jar ./libs/openai-code-review-sdk-1.0-SNAPSHOT.jar
